### ISSUE TITLE
0.3.3 (1.20.1) World Crash

### ISSUE THREAD

**Issue by TheNamesJames** [OreCruncher/DynamicSurroundingsFabric#109]
I have been using this version of the mod flawlessly for about a month, however I updated a few mods and downloaded a few more and now I am unable to load up worlds with Dynamic Surroundings installed. Not sure why this is, but the crash log says that dynamic surroundings is the suspected cause, and disabling it does in fact allow the world to fully load. 

_For context, I had been waiting for the Moog's Structures mods to fix their incompatibility with the Abnormal Team's mods, and today they did just that, so I updated Moog's and installed Abnormal's._

Is there something I am missing?

**Here's the log's output:**
-- Head --
Thread: Render thread
Suspected Mod: 
	Dynamic Surroundings (dsurround), Version: 0.3.3
		at TRANSFORMER/dsurround@0.3.3/org.orecruncher.dsurround.lib.resources.ResourceLookupHelper.findResourcePaths(ResourceLookupHelper.java:26)
Stacktrace:
	at org.orecruncher.dsurround.lib.resources.ResourceLookupHelper.findResourcePaths(ResourceLookupHelper.java:26) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.fabric.services.PlatformServiceImpl.findResourcePaths(PlatformServiceImpl.java:139) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.lib.resources.ServerResourceFinder.find(ServerResourceFinder.java:35) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.lib.resources.ResourceUtilities.findClientTagFiles(ResourceUtilities.java:87) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.lib.resources.ClientTagLoader.loadTagData(ClientTagLoader.java:114) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.lib.resources.ClientTagLoader.getTagData(ClientTagLoader.java:84) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.lib.resources.ClientTagLoader.getMembers(ClientTagLoader.java:42) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at java.util.Map.computeIfAbsent(Unknown Source) ~[?:?] {re:mixin}
	at org.orecruncher.dsurround.config.libraries.impl.TagLibrary.initializeTagCache(TagLibrary.java:204) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.config.libraries.impl.TagLibrary.onConnect(TagLibrary.java:189) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:classloading}
	at org.orecruncher.dsurround.eventing.ClientState.lambda$static$8(ClientState.java:56) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:mixin,re:classloading}
	at org.orecruncher.dsurround.eventing.ClientState.connectionDetector(ClientState.java:105) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:mixin,re:classloading}
	at org.orecruncher.dsurround.eventing.ClientState.lambda$static$4(ClientState.java:38) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231234!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$chp000$dsurround$tickStart(Minecraft.java:11432) ~[client-1.20.1-20230612.114412-srg.jar%23686!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['LeNamesJames'/166, l='ClientLevel', x=-851.70, y=71.00, z=-305.03]]
	Chunk stats: 4096, 1021
	Level dimension: minecraft:overworld
	Level spawn location: World: (-608,64,-80), Section: (at 0,0,0 in -38,4,-5; chunk contains blocks -608,-64,-80 to -593,319,-65), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,-64,-512 to -513,319,-1)
	Level time: 15419 game time, 25981 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23686!/:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin from mod citadel,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin from mod supplementaries,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel from mod oculus,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin from mod starlight,pl:mixin:APP:dsurround.mixins.json:core.MixinClientWorld from mod dsurround,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin from mod flywheel,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin from mod entityculling,pl:mixin:APP:palladiumcore.mixins.json:ClientLevelMixin from mod palladiumcore,pl:mixin:APP:lambdynlights.mixins.json:ClientWorldMixin from mod lambdynlights,pl:mixin:APP:architectury.mixins.json:MixinClientLevel from mod architectury,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:ClientWorldMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin from mod blueprint,pl:mixin:APP:sound_physics_remastered.mixins.json:ClientLevelMixin from mod (unknown),pl:mixin:APP:embeddium.mixins.json:features.render.world.ClientLevelMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23686!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23686!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.17.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain from mod notenoughcrashes,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by OreCruncher** [comment]
Though this is really old, did you have any mods that "fix" Minecraft for bugs or performance? There were conflicts with these mods and the mod authors quickly addressed.
