### ISSUE TITLE
Game will not start

### ISSUE THREAD

**Issue by Solarcraft12** [OreCruncher/DynamicSurroundingsFabric#20]
I am running Majaro linux (5.17 kernel) multimc5 0.6.14-2998 Fabric loader 1.13.3 Minecraft 1.18.1.  I followed the instructions in this video:  [](https://www.youtube.com/watch?v=09jPs3ePfhE) to install this build:  #17.  I had this mod and the fabric api instaled (version 0.46.6).  If anyone can help me I would greatly appreciate it.  Here is my multimc game log:

MultiMC version: 0.6.14-2998

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.32.211.72]

session.minecraft.net resolves to:
    [52.205.99.166, 3.211.39.224, 3.224.239.34]

textures.minecraft.net resolves to:
    [54.230.253.62, 54.230.253.81, 54.230.253.83, 54.230.253.87]

api.mojang.com resolves to:
    [54.230.225.220]

Minecraft folder is:
/home/lucius/.local/share/multimc/instances/Dynamic surroundings test/.minecraft

Java path is:
/usr/lib/jvm/java-17-openjdk/bin/java

Checking Java version...
Java is version 17.0.3, using 64-bit architecture, from N/A.

Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)

DeviceName: Onboard - Video

Subsystem: Dell Device 0a64

NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)

Subsystem: Dell Device 0a64

Kernel driver in use: nvidia

OpenGL version string: 4.6.0 NVIDIA 510.54

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/lucius/.local/share/multimc/instances/Dynamic surroundings test/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  /home/lucius/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar
  /home/lucius/.local/share/multimc/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
  /home/lucius/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar
  /home/lucius/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/lucius/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /home/lucius/.local/share/multimc/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/lucius/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/lucius/.local/share/multimc/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar
  /home/lucius/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/lucius/.local/share/multimc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/lucius/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/lucius/.local/share/multimc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/lucius/.local/share/multimc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/lucius/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar
  /home/lucius/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/lucius/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/lucius/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/lucius/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/lucius/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/lucius/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /home/lucius/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/lucius/.local/share/multimc/libraries/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar
  /home/lucius/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/lucius/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar
  /home/lucius/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar
  /home/lucius/.local/share/multimc/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
  /home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
  /home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
  /home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
  /home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar
  /home/lucius/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/minecraft/1.18.1/minecraft-1.18.1-client.jar

Native libraries:
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/lucius/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Mods:
  [✔️] DynamicSurroundings-Fabric-1.18.2-0.0.4
  [✔️] fabric-api-0.46.6+1.18

Params:
  --username  --version MultiMC5 --gameDir /home/lucius/.local/share/multimc/instances/Dynamic surroundings test/.minecraft --assetsDir /home/lucius/.local/share/multimc/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 4108

Using onesix launcher.

[10:19:49] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[10:19:49] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[10:19:49] [main/INFO]: Loading 53 mods:
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48 via dsurround
	- dsurround 0.0.4
	- fabric 0.46.6+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.9+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.7+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.7+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.12+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.5+737332ce65 via fabric
	- fabric-object-builders-v0 0.7.13+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.15+8906aafd65 via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.9+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.10+c329913d65 via fabric
	- fabricloader 0.13.3
	- java 17
	- minecraft 1.18.1
	- org_openjdk_nashorn_nashorn-core 15.3 via dsurround
[10:19:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/lucius/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:19:49] [main/INFO]: Compatibility level set to JAVA_16
[10:19:52] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdp000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[10:19:54] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:19:56] [Render thread/INFO]: Setting user: LuciusOfLegend
[10:19:58] [Render thread/INFO]: Initializing...
[10:19:58] [Render thread/INFO]: Initialization complete
[10:19:58] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[10:19:59] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[10:20:04] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper':
libflite.so.1: cannot open shared object file: No such file or directory
libflite.so.1: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libfliteWrapper.so) not found in resource path (/usr/lib/multimc/jars/NewLaunch.jar:/home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:/home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:/home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:/home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:/home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:/home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:/home/lucius/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/blocklist/1.0.6/blocklist-1.0.6.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar:/home/lucius/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar:/home/lucius/.local/share/multimc/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar:/home/lucius/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar:/home/lucius/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar:/home/lucius/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar:/home/lucius/.local/share/multimc/libraries/com/ibm/icu/icu4j/69.1/icu4j-69.1.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar:/home/lucius/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/home/lucius/.local/share/multimc/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar:/home/lucius/.local/share/multimc/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/lucius/.local/share/multimc/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:/home/lucius/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/home/lucius/.local/share/multimc/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/home/lucius/.local/share/multimc/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:/home/lucius/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar:/home/lucius/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/home/lucius/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/home/lucius/.local/share/multimc/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/lucius/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar:/home/lucius/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar:/home/lucius/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar:/home/lucius/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/home/lucius/.local/share/multimc/libraries/net/fabricmc/intermediary/1.18.1/intermediary-1.18.1.jar:/home/lucius/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar:/home/lucius/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar:/home/lucius/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.8.1/tiny-remapper-0.8.1.jar:/home/lucius/.local/share/multimc/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar:/home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar:/home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar:/home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar:/home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar:/home/lucius/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar:/home/lucius/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.13.3/fabric-loader-0.13.3.jar:/home/lucius/.local/share/multimc/libraries/com/mojang/minecraft/1.18.1/minecraft-1.18.1-client.jar)
[10:20:05] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Cloth Config v6, §6Dynamic Surroundings§r: §eFabric Edition, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader)
[10:20:05] [Render thread/INFO]: Processing minecraft:sounds.json
[10:20:06] [Render thread/INFO]: Processing dsurround:sounds.json
[10:20:06] [Render thread/INFO]: Number of SoundEvents cached: 1282
[10:20:06] [Render thread/INFO]: Processing minecraft:dsconfigs/biomes.json
[10:20:06] [Render thread/INFO]: 40 biome configs loaded; version is now 1
[10:20:06] [Render thread/INFO]: Processing minecraft:dsconfigs/dimensions.json
[10:20:06] [Render thread/INFO]: Processing minecraft:dsconfigs/blocks.json
[10:20:06] [Render thread/WARN]: net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862; net/minecraft/class_6862
[10:20:06] [Render thread/INFO]: 20 block configs loaded; version is now 1
[10:20:06] [Render thread/INFO]: Processing minecraft:dsconfigs/items.json
[10:20:06] [Render thread/INFO]: 8 item configs loaded; version is now 1
[10:20:06] [Render thread/INFO]: Processing minecraft:dsconfigs/effects.json
[10:20:06] [Render thread/INFO]: 4 entity config rules loaded; version is now 1
[10:20:06] [Render thread/ERROR]: Unhandled game exception
java.lang.NoSuchFieldError: field_15503
	at org.orecruncher.dsurround.processing.scanner.CeilingScanner.<clinit>(CeilingScanner.java:50) ~[DynamicSurroundings-Fabric-1.18.2-0.0.4.jar:?]
	at org.orecruncher.dsurround.processing.Scanners.<clinit>(Scanners.java:21) ~[DynamicSurroundings-Fabric-1.18.2-0.0.4.jar:?]
	at org.orecruncher.dsurround.processing.Handlers.init(Handlers.java:55) ~[DynamicSurroundings-Fabric-1.18.2-0.0.4.jar:?]
	at org.orecruncher.dsurround.processing.Handlers.<init>(Handlers.java:38) ~[DynamicSurroundings-Fabric-1.18.2-0.0.4.jar:?]
	at org.orecruncher.dsurround.lib.Singleton.get(Singleton.java:27) ~[DynamicSurroundings-Fabric-1.18.2-0.0.4.jar:?]
	at org.orecruncher.dsurround.processing.Handlers.initialize(Handlers.java:42) ~[DynamicSurroundings-Fabric-1.18.2-0.0.4.jar:?]
	at org.orecruncher.dsurround.Client.onComplete(Client.java:111) ~[DynamicSurroundings-Fabric-1.18.2-0.0.4.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-1.4.1+713c266865-8dceb60b57f69f81.jar:?]
	at net.minecraft.class_310.handler$zdo000$onStart(class_310.java:4008) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:712) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[10:20:07] [Render thread/INFO]: Stopping!
[10:20:07] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.class_1060.close(class_1060.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.close(class_310.java:1043) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1490(class_310.java:1022) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:254) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 0.
Clipboard copy at: 13 Mar 2022 10:20:17 -0400

**Comment by Solarcraft12** [comment]
Also, is there any way to do something like spoilers?  Just some way so you don't have to scroll past the game log every time you wanna see responses?

**Comment by Solarcraft12** [comment]
I actually thought of one thing just now.  If this works...  Then I'm an idiot.

**Comment by Solarcraft12** [comment]
OooooooOook.  All I had to do was switch to 1.18.2.  Some of my mods still don't work on that version however, so I was wondering if there is a way to get the 1.18.1 version anywhere?

**Comment by Solarcraft12** [comment]
Sorry, I will close this issue and open a new one requesting 1.18.1 build.

**Comment by HarvelsX** [comment]
Try https://github.com/HarvelsX/DynamicSurroundingsFabric/releases/tag/1.18.1

**Comment by Solarcraft12** [comment]
I already got it figured out but i will use that in the future.  Thanks a lot!
