### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by showierdata9978** [OreCruncher/DynamicSurroundingsFabric#31]
context below

```
16:16:59.650
[CHAT] requesting resend of blocks around you
16:17:11.297
[CHAT] requesting resend of blocks around you
16:17:11.745
[CHAT] requesting resend of blocks around you
16:17:11.943
[CHAT] requesting resend of blocks around you
16:17:13.339
[CHAT] requesting resend of blocks around you
16:17:13.542
[CHAT] requesting resend of blocks around you
16:17:13.707
[CHAT] requesting resend of blocks around you
16:17:14.006
Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
16:17:14.097
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "org.orecruncher.dsurround.processing.scanner.RandomBlockEffectScanner.tick()" because "this.farEffects" is null
	at org.orecruncher.dsurround.processing.AreaBlockEffects.process(AreaBlockEffects.java:38)
	at org.orecruncher.dsurround.processing.Handlers.onTick(Handlers.java:109)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zon000$onEndTick(class_310.java:5473)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


```

other mods
![image](https://user-images.githubusercontent.com/68120127/209235942-b2d71788-8e2b-4db6-8a69-1f23e6ae5a86.png)

**Comment by showierdata9978** [comment]
#15

**Comment by showierdata9978** [comment]
#9
