### ISSUE TITLE
[1.20.1] [Sinytra] Crash when joining world

### ISSUE THREAD

**Issue by MrFastZombie** [OreCruncher/DynamicSurroundingsFabric#98]
Minecraft 1.20.1
NeoForge 47.1.100
Sinytra Connector Beta 37
Connector Extras 1.9.3, Forgified Fabric API 0.92.0

When joining a server I get this error:

```
java.lang.NullPointerException: Cannot invoke "java.util.Collection.stream()" because "this.rootPaths" is null
	at org.orecruncher.dsurround.lib.resources.ResourceLookupHelper.findResourcePaths(ResourceLookupHelper.java:26) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.fabric.services.PlatformServiceImpl.findResourcePaths(PlatformServiceImpl.java:139) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.lib.resources.ServerResourceFinder.find(ServerResourceFinder.java:35) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.lib.resources.ResourceUtilities.findClientTagFiles(ResourceUtilities.java:87) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.lib.resources.ClientTagLoader.loadTagData(ClientTagLoader.java:114) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.lib.resources.ClientTagLoader.getTagData(ClientTagLoader.java:84) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.lib.resources.ClientTagLoader.getMembers(ClientTagLoader.java:42) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.Map.computeIfAbsent(Map.java:1054) ~[?:?] {re:mixin}
	at org.orecruncher.dsurround.config.libraries.impl.TagLibrary.initializeTagCache(TagLibrary.java:204) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.config.libraries.impl.TagLibrary.onConnect(TagLibrary.java:189) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.eventing.ClientState.lambda$static$8(ClientState.java:56) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.eventing.ClientState.connectionDetector(ClientState.java:105) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at org.orecruncher.dsurround.eventing.ClientState.lambda$static$4(ClientState.java:38) ~[DynamicSurroundings-Fabric-1.20.1-0.3.3_mapped_srg_1.20.1.jar%231879!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.Minecraft.handler$ggj000$dsurround$tickStart(Minecraft.java:26432) ~[client-1.20.1-20230612.114412-srg.jar%231052!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java) ~[client-1.20.1-20230612.114412-srg.jar%231052!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%231052!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%231052!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain from mod notenoughcrashes,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
```

Full crash report: https://gist.github.com/MrFastZombie/ee8b8addc39a7c46cdbe7eec1eac8585

My crash occured when joining a server, but I found [someone else reporting a similar crash](https://www.reddit.com/r/Minecraft/comments/1b5bqbm/crash_supportminecraft_modded_need_help/) that occured in singleplayer, so I don't think this is exclusive to multiplayer.

I've tried setting up a test instance and adding mods mentioned in the log, but I haven't been able to reproduce this crash that way so far.

**Comment by OreCruncher** [comment]
Hmm. This would be weird.  It would mean that the resource manager reload hook wasn't being called. Could you update ModernFix to the latest version?

**Comment by MrFastZombie** [comment]
I've updated Modern Fix, but I still seem to have the error unfortunately. 

Here's my [latest.log](https://api.mclo.gs/1/raw/5a9UaxN) in case that helps.

**Comment by MrFastZombie** [comment]
It seems to be related to Thermal Foundation in my case, but even after adding it to my test instance I can not reproduce it there. In my main instance, removing it fixes this crash as well as a few other crashes. The other user from that reddit thread does not have Thermal Foundation, so I don't really know what to make of this.
